def save_dashboard(self, filename: str = "dashboard.html"):
    """ダッシュボードHTML保存（エンコーディング対応版）"""
    html_content = self.generate_dashboard_html()
    
    try:
        # UTF-8エンコーディングで確実に保存
        with open(filename, 'w', encoding='utf-8', errors='replace') as f:
            f.write(html_content)
        print(f"📊 ダッシュボード保存完了: {filename}")
        return filename
    except Exception as e:
        print(f"❌ ダッシュボード保存エラー: {e}")
        # ASCII文字のみでフォールバック版を作成
        fallback_html = self.create_ascii_dashboard()
        with open(filename, 'w', encoding='ascii', errors='ignore') as f:
            f.write(fallback_html)
        print(f"📊 フォールバック版ダッシュボード保存: {filename}")
        return filename

def create_ascii_dashboard(self):
    """ASCII文字のみのフォールバックダッシュボード"""
    analytics = self.generate_sample_analytics()
    
    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exterior AI Marketing System - Analytics Dashboard</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f0f0f0; }}
        .dashboard {{ max-width: 1000px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; }}
        .header {{ background: #2E8B57; color: white; padding: 20px; text-align: center; border-radius: 5px; }}
        .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }}
        .metric {{ background: #f8f9fa; padding: 20px; border-radius: 5px; text-align: center; }}
        .value {{ font-size: 2em; font-weight: bold; color: #2E8B57; }}
    </style>
</head>
<body>
    <div class="dashboard">
        <div class="header">
            <h1>Exterior AI Marketing System</h1>
            <p>Analytics Dashboard</p>
        </div>
        
        <div class="metrics">
            <div class="metric">
                <div>Monthly Sales</div>
                <div class="value">¥{analytics['total_sales']:,}</div>
            </div>
            <div class="metric">
                <div>ROI</div>
                <div class="value">{analytics['roi']}%</div>
            </div>
            <div class="metric">
                <div>Contracts</div>
                <div class="value">{analytics['contracts']}</div>
            </div>
        </div>
        
        <div style="text-align: center; margin-top: 30px;">
            <p>Generated by Lady AI Assistant</p>
            <p>Exterior Marketing Automation System</p>
        </div>
    </div>
</body>
</html>
"""
